# Creating the Gradio interface

import gradio as gr

from src.models.app_predict import (
    load_model,
    predict_intent,
)


# Load the model once when the app starts.
model = load_model()


def classify_message(message):
    """
    Handle customer input from the Gradio interface.
    """
    try:
        predicted_intent = predict_intent(
            message,
            model,
        )

        return predicted_intent

    except (ValueError, TypeError) as error:
        raise gr.Error(str(error))


with gr.Blocks(
    title="SupportSense"
) as demo:

    gr.Markdown(
        """
        # SupportSense

        ### AI-powered Banking Support Intent Classifier

        Enter a customer-support message to identify
        the most likely BANKING77 intent.

        **Model:** TF-IDF + Linear SVM

        This is an educational ML portfolio application,
        not a live banking service.
        """
    )

    message_input = gr.Textbox(
        label="Customer message",
        placeholder=(
            "Example: My card has not arrived yet"
        ),
        lines=4,
        max_lines=8,
    )

    classify_button = gr.Button(
        "Classify Intent",
        variant="primary",
    )

    prediction_output = gr.Textbox(
        label="Predicted Intent",
        interactive=False,
    )

    classify_button.click(
        fn=classify_message,
        inputs=message_input,
        outputs=prediction_output,
    )

    message_input.submit(
        fn=classify_message,
        inputs=message_input,
        outputs=prediction_output,
    )

    gr.Examples(
        examples=[
            ["My card has not arrived yet"],
            ["I forgot my card PIN"],
            ["The ATM did not give me my cash"],
            ["I want to exchange pounds for euros"],
            ["I was charged twice for a purchase"],
        ],
        inputs=message_input,
    )

    gr.Markdown(
        """
        ---
        **Note:** Predictions are generated by a machine-learning
        classifier and may be incorrect. Do not enter personal,
        financial, or confidential information.
        """
    )


if __name__ == "__main__":
    demo.launch()